### PR TITLE
Add test for PropertyBasedJobInclusionStrategy class

### PR DESCRIPTION
**Pull request by yashpal2104**
### Testing done

Add test for PropertyBasedJobInclusionStrategy class

Fixes JIRA issue [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira

### CODE REVIEW

**Review by MarkEWaite — COMMENTED** [review]
I've added several assertions to the test class.  I'll need to give more thought to the addition of public constructors for test purposes.  I think that we might be able to move the test class so that it could use a package protected constructor. However, that needs more time.

**Comment by yashpal2104** [comment]
Alright, what suits the best will work. I thought of making this a draft PR but yeah I thought the changes were valid should we make this a draft PR or is there something else we need to do?

**Comment by MarkEWaite** [comment]
@yashpal2104 I've modified the class in src/main so that it is no longer providing a public method.  That felt too invasive for a test related change.  I've created a package protected method that is called from the test.  Because it is package protected, it is only available to classes that are in the same package.

If those changes are acceptable to you, then I believe this is ready to merge.  If they aren't acceptable, you are welcome to revert them or submit additional changes to further improve them.

**Comment by yashpal2104** [comment]
Looks good to me for now. I have added some comments to the changes we made so that we can pinpoint any issues if something goes wrong. If you think this is unnecessary you can remove them.

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
