### PR TITLE
[JENKINS-69751]: Add sorting for blocked projects

### PR DESCRIPTION
**Pull request by Si-So**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

**What was wrong**
When jobs were selected for moving from blocked to buildable list, the default sorting method was used, so that those jobs which have been in the queue for the longest time were moved to buildable first instead of those with highest priority.

**What has been done**
1. The default method for sorting blocked jobs has been overridden and now the same method is used for both buildable and blocked lists.
2. A test was written for the new functionality

This PR is based on this older PR that wasn't merged: https://github.com/jenkinsci/priority-sorter-plugin/pull/69

[JENKINS-69751](https://issues.jenkins.io/browse/JENKINS-69751)

### CODE REVIEW

**Comment by Si-So** [comment]
@MarkEWaite: Is there anything else you need from me?

**Comment by MarkEWaite** [comment]
@Si-So I will be out of the office and away from most computers until at least Oct 27.  Once I return, it will likely be a few weeks before I can review the pull request.

**Comment by Si-So** [comment]
@MarkEWaite: Can I assist you in any way?

**Comment by MarkEWaite** [comment]
@Si-So as part of the update in #254 , I integrated your changes from this pull request into #69.  I propose to close this pull request and we can evaluate #69 to see if it should be merged with your changes and the original work from @monluk

**Comment by MarkEWaite** [comment]
Closing pull request in favor of #69

**Pull request closed without merging**
