### PR TITLE
Add a MavenReleaseCauseStrategy

### PR DESCRIPTION
**Pull request by markiewb**
Adds a CauseStrategy which uses the configured priority when the build is triggered by a Maven Release.

It looks like this

Please review.

-- https://issues.jenkins-ci.org/browse/JENKINS-53596

### CODE REVIEW

**Comment by markiewb** [comment]
@oleg-nenashev Please review my pull-request. 

The CI pipeline fails with an error 

testCliSanity(org.jvnet.hudson.test.PluginAutomaticTestBuilder$CliSanityTest)  Time elapsed: 0.065 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/maven/artifact/repository/Authentication

at

https://ci.jenkins.io/blue/rest/organizations/jenkins/pipelines/Plugins/pipelines/priority-sorter-
plugin/branches/PR-46/runs/1/nodes/8/log/?start=0

But nothing in that related area has been changed by my PR. Please start a build of the stable master to check if this error also occurs there. I guess so and thus it is an infrastructure problem or another incompatibility

**Comment by markiewb** [comment]
@oleg-nenashev Please review my pull-request.

**Comment by oleg-nenashev** [comment]
Sorry, this plugin is not actively maintained nowadays. It is open for adoption for almost 1 year.

I might be able to review/release it after the NY, but I cannot commit on dates

**Comment by MarkEWaite** [comment]
Closing the pull request due to inactivity.  Can be reopened if others are interested in moving forward with it.  The `m2release` plugin is up for adoption so does not seem like a strong candidate to add this feature to the plugin

**Pull request closed without merging**
