### PR TITLE
[JENKINS-36570] - Cleanup references to AbstractProject in the core plugin classes

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Generally this change is not binary compatible, and likely it requires 4.0. Not sure if the plugin can be really used in Pipeline without this fix. 

https://issues.jenkins-ci.org/browse/JENKINS-36570

CC @reviewbybees, @vitalii-vitrenko and @timothyclarke

### CODE REVIEW

**Comment by aheritier** [comment]
🐝

**Comment by stephenc** [comment]
:bee: @reviewbybees done

**Comment by oleg-nenashev** [comment]
Will check the JobProperty API in order to say if it really breaks the compatibility

**Comment by oleg-nenashev** [comment]
After checking the parent class I conclude it's safe to merge this PR as is. Compatibility is not broken by this change

**Pull request merged**
