### PR TITLE
[JENKINS-54571] Add Configuration as Code plugin support

### PR DESCRIPTION
**Pull request by fr123k**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

This PR implements the needed changes to support the configuration of this plugin
with the [configuration-as-code-plugin](https://github.com/jenkinsci/configuration-as-code-plugin).

For details about how to provide the CasC configuration checkout the `ConfigurationAsCodeTest` junit
and the used test ressources in the `src/test/resources/jcasc` folder.

This PR also implements the following jira ticket with the title `Problem with jcasc compatibility plugin and job priority in Jenkins`.
[JENKINS-54571](https://issues.jenkins.io/browse/JENKINS-54571)

### CODE REVIEW

**Comment by robodair** [comment]
@fr123k I just want to say thank you for putting the work in to make this happen! This will be really useful.

**Comment by easybe** [comment]
We have been waiting for this! Is there anything I can do to speed up the merge?

**Comment by julianxhokaxhiu** [comment]
Yes please, I actually need to use this plugin as well and I thought it had JCasC support. Please considering speeding up this PR!

**Comment by MarkEWaite** [comment]
@julianxhokaxhiu and @easybe, one way you can accelerate the merge of the plugin is by using the incremental build of the  plugin and reporting in this pull request that you've been successful with it.

**Comment by julianxhokaxhiu** [comment]
Thanks for the feedback! I'm really sorry but I'm not an active Java developer therefore I can't really help other than testing the plugin. Although I noticed you found already some issues so I'll wait for the next iteration.

Looking forward to this PR. Thanks and cheers!

**Comment by easybe** [comment]
I sucessfull mange to configure [PrioritySorter-4.0.2-rc378.69c91937a110](https://ci.jenkins.io/job/Plugins/job/priority-sorter-plugin/view/change-requests/job/PR-62/lastSuccessfulBuild/artifact/org/jenkins-ci/plugins/PrioritySorter/4.0.2-rc378.69c91937a110/PrioritySorter-4.0.2-rc378.69c91937a110.hpi) installed on Jenkins 2.303.3.

When using the JCasC's "View Configuration" feature, I get the following output for our configuration: 
```
priorityConfiguration:
  jobGroups:
  - jobGroupStrategy: "allJobs"
    priority: -1
    priorityStrategies:
    - buildParameterStrategy:
        id: 0
        priorityStrategy:
          buildParameterStrategy:
            parameterName: "PRIORITY"
    - userIdCauseStrategy:
        id: 1
        priorityStrategy:
          userIdCauseStrategy:
            priority: 1
    usePriorityStrategies: true
prioritySorterConfiguration:
  onlyAdminsMayEditPriorityConfiguration: true
  strategy:
    absoluteStrategy:
      defaultPriority: 2
      numberOfPriorities: 4
```
Even though this does not look as bad as what @MarkEWaite reported, it does not seem to be correct. The following configuration works for me: 
```
priorityConfiguration:
  jobGroups:
    - jobGroupStrategy: "allJobs"
      priority: -1
      priorityStrategies:
        - buildParameterStrategy:
            parameterName: "PRIORITY"
        - userIdCauseStrategy:
            priority: 1
      usePriorityStrategies: true
prioritySorterConfiguration:
  onlyAdminsMayEditPriorityConfiguration: true
  strategy:
    absoluteStrategy:
      defaultPriority: 2
      numberOfPriorities: 4
```

**Comment by MarkEWaite** [comment]
I've integrated this pull request into my test setup with good results.

* [Plugin version](https://github.com/MarkEWaite/docker-lfs/blob/4d7e37f89d594d91ad363cc3dba1e4548eb557f6/plugins.txt#L1) included for testing
* [Configuration as code definition](https://github.com/MarkEWaite/docker-lfs/blob/4d7e37f89d594d91ad363cc3dba1e4548eb557f6/ref/configuration-as-code/unclassified.yaml#L161) for my jobs (all folder based)

Would love to hear that others have tested the pull request as well.

**Comment by MarkEWaite** [comment]
@julianxhokaxhiu or @easybe have you done any further experiments with recent incremental builds of this pull request?  It is working for me in my environment with my configuration of 5 priority levels based on folders.

**Comment by julianxhokaxhiu** [comment]
Hello, I'm sorry but I didn't had a chance as not having it in the registry makes it more complicated for me to be tested. So I'll be able to do so only when published and officially available through Jenkins plugins.

**Comment by MarkEWaite** [comment]
Understood @julianxhokaxhiu .  Thanks for your reply and thanks for your involvement.

I'm confident that my use case is a very narrow slice of the potential use cases for the plugin.  I don't have the time to do the more detailed compatibility testing to assure that the changes work for the more widely available use cases.  My issue is resolved by using the incremental build of this pull request.

Others that need configuration as code for priority sorter can use the incremental build until someone declares that they have performed the wider testing.  Thanks again for participating in the Jenkins project!

**Comment by easybe** [comment]
I tried the 4.1.1-rc490.1a_a_0a_c9d4a_8e incremental build.

Unfortunately, "Configuration as Code -> View Configuration" is still looking the same as reported in https://github.com/jenkinsci/priority-sorter-plugin/pull/62#issuecomment-981873161:

```
priorityConfiguration:
    jobGroups:
    - jobGroupStrategy: "allJobs"
      priority: -1
      priorityStrategies:
      - buildParameterStrategy:
          id: 0
          priorityStrategy:
            buildParameterStrategy:
              parameterName: "PRIORITY"
      - userIdCauseStrategy:
          id: 1
          priorityStrategy:
            userIdCauseStrategy:
              priority: 1
      usePriorityStrategies: true
  prioritySorterConfiguration:
    onlyAdminsMayEditPriorityConfiguration: true
    strategy:
      absoluteStrategy:
        defaultPriority: 2
        numberOfPriorities: 4
```

Thanks for the effort.

Cheers,
Ezra.

**Comment by bdamian** [comment]
Big up to the author!

However :slightly_smiling_face:  I'm facing the same issue as @easybe. My configuration is very similar to that one. I tried also version 4.1.1-rc506.e9d3571a_3387.

It seems that input configuration for the plugin and the casc-output use different code. There is a [TODO-note](https://github.com/jenkinsci/priority-sorter-plugin/blob/b0bef79868206634b9146dcda8d27b3288be25ae/src/main/java/jenkins/advancedqueue/JobGroup.java#L199) about not using `@DataBoundConstructor` in `JobGroup`, which is probably the cause of the problem.

Do you plan to switch to DataBoundConstructor globally in the PrioritySorter's code?


Best,
Damian

**Comment by MarkEWaite** [comment]
> Do you plan to switch to DataBoundConstructor globally in the PrioritySorter's code?

I'm willing to consider contributions from others that improve the current situation, in whatever form they take.  I won't be spending time myself on implementing changes, but am willing to include changes in my own configuration and am willing to do some code review related to improvements proposed by others.  Configuration as code in the priority sorter plugin is not as high priority for me as other items that I'm doing.

**Comment by MarkEWaite** [comment]
Closing in favor of 

* #262

**Pull request closed without merging**
