### PR TITLE
Add test for JobInclusionFolderProperty class

### PR DESCRIPTION
**Pull request by yashpal2104**
### Testing done

Added a new test class for JobInclusionFolderProperty class and added a constructor in ItemInfo class.

JIRA issue [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira

### CODE REVIEW

**Comment by yashpal2104** [comment]
@MarkEWaite I can modify these tests to isolate tests by creating a new FreeStyleProject before each test to execute? If resource usage is a concern, otherwise creating new project it ensures test isolation and prevents side effects from shared state and maintaining test reliability and accuracy. That is why I have left a tearDown() method in the class if at any point in future if anyone considers this approach more reliable?

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
The output when I run those tests locally includes a null pointer exception that is not causing the test to fail.  I don't see the null pointer exception in the output from ci.jenkins.io but I see it locally.  That will need to be resolved before this pull request can be considered further.  The null pointer exception message that I see is:

```
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "jenkins.advancedqueue.testutil.TestRunListener.actual" is null
	at jenkins.advancedqueue.testutil.TestRunListener.onStarted(TestRunListener.java:33)
	at hudson.model.listeners.RunListener.lambda$fireStarted$2(RunListener.java:246)
	at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
	at jenkins.util.Listeners.notify(Listeners.java:67)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:244)
	at hudson.model.Run.execute(Run.java:1892)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
```

**Comment by yashpal2104** [comment]
> The output when I run those tests locally includes a null pointer exception that is not causing the test to fail.  I don't see the null pointer exception in the output from ci.jenkins.io but I see it locally.  That will need to be resolved before this pull request can be considered further.  The null pointer exception message that I see is:
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "jenkins.advancedqueue.testutil.TestRunListener.actual" is null
> 	at jenkins.advancedqueue.testutil.TestRunListener.onStarted(TestRunListener.java:33)
> 	at hudson.model.listeners.RunListener.lambda$fireStarted$2(RunListener.java:246)
> 	at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
> 	at jenkins.util.Listeners.notify(Listeners.java:67)
> 	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:244)
> 	at hudson.model.Run.execute(Run.java:1892)
> 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
> 	at hudson.model.ResourceController.execute(ResourceController.java:101)
> 	at hudson.model.Executor.run(Executor.java:442)
> ```

I did get that error locally but after (hours of) some modifications it disappeared so yes I don't have a solution right now I will get to it as it is occurring now

**Comment by MarkEWaite** [comment]
Null pointer exception is fixed as far as I can tell.

**Comment by yashpal2104** [comment]
Thank you for helping out, I think I should n't have tried to change the methods in the class excuse me this time I did try something out and it didn't work out.

**Comment by MarkEWaite** [comment]
> Thank you for helping out, I think I should n't have tried to change the methods in the class excuse me this time I did try something out and it didn't work out.

No problem.  I've truly pleased that you are exploring and that you're not shy about making changes that improve testability.

**Comment by yashpal2104** [comment]
There are no conflicts locally, and the null pointer exception has been resolved. I believe this PR is ready to be merged.

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Pull request merged**
