### PR TITLE
Support configuration as code

### PR DESCRIPTION
**Pull request by Kamyki**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

This PR implements the needed changes to support the configuration of this plugin
with the [configuration-as-code-plugin](https://github.com/jenkinsci/configuration-as-code-plugin). It is my rework of previous work [PR-62](https://github.com/jenkinsci/priority-sorter-plugin/pull/62) by @fr123k . I submit it as a separate PR for my convenience, but if necessary I can apply patch on the original. 

Initial pull request had problem with exporting configuration by `jenkins/manage/configuration-as-code/viewExport`, causing serialisation errors. To mitigate that, following this [comment](https://github.com/jenkinsci/priority-sorter-plugin/pull/62#issuecomment-1551259650) I had added DataBoundConstructor and DataBoundSetter annotation to some classes.

I was aiming to preserve format of xml configuration for plugin, thus I haven't edited class hierarchy, but it results in slightly uglier casc configuration format - see tests.

This PR also implements the following jira ticket with the title Problem with jcasc compatibility plugin and job priority in Jenkins.
[JENKINS-54571](https://issues.jenkins.io/browse/JENKINS-54571)

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks very much for the pull request.  I've added one of the changes from the master branch back into the pull request so that the new icon renders correctly on the pages.

I've started testing the incremental build of this pull request in my configuration as code environment and it looks very good.

The documentation in the README file needs a section that describes configuration as code examples.  Would you be willing to add that documentation?

@julianxhokaxhiu you mentioned in https://github.com/jenkinsci/priority-sorter-plugin/pull/62#issuecomment-981061974 that you were waiting for the next iteration.  This is the next iteration.  I'd love to have your help testing it to confirm that compatibility is retained and that configuration as code works as expected.

@easybe you had tested the earlier pull request ( #62 ).  It would be very nice if you could help with the testing of this pull request.

**Comment by easybe** [comment]
> @easybe you had tested the earlier pull request ( #62 ). It would be very nice if you could help with the testing of this pull request.

Unfortunately, we no longer use Jenkins in the company I work for now. But, I reached out to my former co-workers.

Thanks for finally wrapping this up!

**Comment by julianxhokaxhiu** [comment]
> Unfortunately, we do not use Jenkins in the company I work for now. But, I reached out to my former co-workers.
> 
> Thanks for finally wrapping this up!

Same here, but hopefully somehow will reach out soon :) Nevertheless, thanks for making this possible!

**Comment by julianxhokaxhiu** [comment]
> Unfortunately, we do not use Jenkins in the company I work for now. But, I reached out to my former co-workers.
> 
> Thanks for finally wrapping this up!

Same here, hopefully someone will reach out soon :) Nevertheless, thanks for making this possible!

**Comment by Kamyki** [comment]
I added README section with sample casc configuration. Is there something else I can do to speed up acceptance of this PR ? Are we just waiting for more people to test it?

**Comment by MarkEWaite** [comment]
> I added README section with sample casc configuration. Is there something else I can do to speed up acceptance of this PR ? Are we just waiting for more people to test it?

That was what I was seeking, since there were two users during the life of the pull request who had expressed interest in configuration as code and seemed like good candidates to test it.  However, since they are both unavailable to test it, I think your testing and my testing are enough to declare it sufficient to release.

**Review by MarkEWaite — APPROVED** [review]
Completed my interactive testing, confirmed that the configuration as code works in my installation, and implemented two additional tests to be sure.

**Pull request merged**
