### PR TITLE
[JENKINS-40284] - Fix blocked weights with FQ strategies

### PR DESCRIPTION
**Pull request by debanne**
When a weight reached 1.00005 for instance, it was never increased
due to the comparison on floats.
Also, the weight was no more increased when the step became too small
compared to the minimum weight. As we are not using integers but
floats, the step must remain proportional to the weight.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by oleg-nenashev** [comment]
LGTM 👍

**Comment by Dohbedoh** [comment]
👍

**Comment by alecharp** [comment]
@oleg-nenashev @emsa23 do you thing you could merge this PR and release the plugin?

**Comment by oleg-nenashev** [comment]
I can

**Pull request merged**
