### PR TITLE
[JENKINS-58512] - Fix the issues that can not find page which from a extension plugin

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
> Is there a Jira link with detailed description and repro steps?

Noop

**Comment by Gh0stWalk3r** [comment]
Looks like this could resolve https://issues.jenkins-ci.org/browse/JENKINS-58512 but I have have not tested it.

**Review by oleg-nenashev — COMMENTED** [review]
I'd guess the root cause is not passing the 'it' argument: https://stapler.kohsuke.org/jelly-taglib-ref.html#jelly:include

**Review by oleg-nenashev — APPROVED** [review]
Changed the implementation to 'it'

**Pull request merged**
