### PR TITLE
[JENKINS-69751] Add sorting for blocked projects

### PR DESCRIPTION
**Pull request by monluk**
## [JENKINS-69751](https://issues.jenkins.io/browse/JENKINS-69751) Add sorting for blocked projects

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

**What was wrong**
When jobs were selected for moving from _blocked_ to _buildable_ list, the default sorting method was used, so that those jobs which have been in the queue for the longest time were moved to _buildable_ first instead of those with highest priority.

**What has been done**
The default method for sorting _blocked_ jobs has been overridden and now the same method is used for both _buildable_ and _blocked_ lists.

### CODE REVIEW

**Comment by olivierdagenais** [comment]
Hello, I was having difficulty using this plugin to make sure some runs of a given job would start before others when I cranked up the logging and came to the same conclusion that our friends @monluk and @Si-So did: there was a gap in the implementation whereby we also need to sort _blocked_ runs (it seems our use of "Do not allow concurrent builds" makes new runs show up as blocked).

I built an HPI from this pull request's branch, overwrote the version 5.0.0 plugin I had, restarted Jenkins and all of a sudden my configuration is working!

All this to say that I am eagerly anticipating a release of the Priority Sorter plugin for Jenkins which contains the changes in this pull request!

Is there anything I can do to help move this along?  Are we satisfied with the tests provided in the PR?  Do we want more documentation??  Do we want some torture/stress tests???  I'm happy to help.

Thanks!
Oli

**Comment by MarkEWaite** [comment]
> Is there anything I can do to help move this along? Are we satisfied with the tests provided in the PR? Do we want more documentation?? Do we want some torture/stress tests??? I'm happy to help.

@olivierdagenais, your interactive testing is enough to prompt me to merge and release it.  I'd love to have additional documentation that describes the new behavior, but that can be a separate pull request.

**Review by MarkEWaite — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Comment by Si-So** [comment]
Thanks for the merge :)

When do you plan to release a new version of the plugin?

**Comment by MarkEWaite** [comment]
> Thanks for the merge :)
> 
> When do you plan to release a new version of the plugin?

I want to do some basic testing of the pre-release in my environment over the next few days.  I expect to release a version by the end of the week.

**Comment by olivierdagenais** [comment]
> I'd love to have additional documentation that describes the new behavior, but that can be a separate pull request.

Posted as #318

**Comment by Si-So** [comment]
Hey, 
this might be a little bit petty, but is it possible to add me to the list of contributors for 5.1.0? 

I feel like that creating the unit test for monluk's changes added value. 

If you don't add me, it is also fine :)

**Comment by MarkEWaite** [comment]
> Hey, this might be a little bit petty, but is it possible to add me to the list of contributors for 5.1.0?
> 
> I feel like that creating the unit test for monluk's changes added value.

Thanks for asking!  I agree wholeheartedly that you should be listed.  I've added you to the [changelog](https://github.com/jenkinsci/priority-sorter-plugin/releases/tag/PrioritySorter-5.1.0).  Thanks very much for your contribution!

**Comment by Si-So** [comment]
Thank you :)

**Pull request merged**
